name: cd

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  PYTHON_VERSION: 3.9
  TERADATAML_VERSION: 17.0.0.4
  SKLEARN2PMML_VERISON: 0.79.0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            TERADATAML_VERSION=${{ env.TERADATAML_VERSION }}
            SKLEARN2PMML_VERISON=${{ env.SKLEARN2PMML_VERISON }}
          tags: teradata/python-sklearn2pmml:latest, teradata/python-sklearn2pmml:${{ env.PYTHON_VERSION }}-${{ env.TERADATAML_VERSION }}